name: role-path-guard
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 2}
      - name: path guard
        run: |
          ROLE="${{ github.event.pull_request.labels.*.name || '' }}"
          if [[ "$ROLE" == *"review"* ]]; then
            git diff --name-only -r $(git merge-base HEAD^ HEAD) | grep -q '^src/' && exit 1
          fi