name: release
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SBOM
        run: |
          npm install -g @cyclonedx/bom
          cyclonedx-bom -o sbom.xml
      - name: bundle strict workflow patch
        run: |
          git diff $(git rev-list --max-parents=0 HEAD)..HEAD > strict_workflow.patch
          last=$(git describe --abbrev=0 --tags || echo $(git rev-list --max-parents=0 HEAD))
          git diff $last..HEAD > strict_workflow.patch
      - uses: actions/upload-artifact@v4
        with:
          name: strict_workflow_patch
          path: strict_workflow.patch
      - name: sign SBOM
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob -key cosign.key sbom.xml > sbom.sig
      - uses: actions/upload-artifact@v4
        with:
          name: sbom_signature
          path: sbom.sig