name: STP-Guard

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history to check all commits
          
      - name: Check lifecycle documentation exists
        run: |
          if ! test -f docs/agents/01_task-lifecycle.md; then
            echo '❌ Lifecycle spec missing: docs/agents/01_task-lifecycle.md'
            exit 1
          fi
          echo '✅ Lifecycle documentation found'
          
      - name: Validate STP markers
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          # Use the validation script
          ./tools/validate-stp-markers.sh "$PR_BODY" "$BASE_SHA" "$HEAD_SHA"